groups:
  - name: recordings
    rules:
      - record: job:http_requests:rate1m
        expr: sum(rate(http_requests_total[1m])) by (job)
      - record: job:http_request_duration_seconds:p95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job))
