ARG CUDA_MINOR=12.4
ARG CUDNN_MAJOR=9
ARG UBUNTU_MAJOR=22
ARG ONNXRUNTIME_VER=1.18.0

FROM nvidia/cuda:${CUDA_MINOR}.0-cudnn${CUDNN_MAJOR}-devel-ubuntu${UBUNTU_MAJOR}

RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir onnxruntime-gpu==${ONNXRUNTIME_VER}

CMD ["/bin/bash"]
