version: "3.9"
services:
  bff:
    build: ./services/bff
    env_file: [.env]
    ports: ["8088:8088"]
    depends_on: [terminusdb, neo4j, opensearch, qdrant, nats, postgres, redis]

  terminusdb:
    image: terminusdb/terminusdb-server:latest
    environment: [ "TERMINUSDB_SERVER_PORT=6363" ]
    ports: ["6363:6363"]
    volumes: ["terminus:/data"]

  neo4j:
    image: neo4j:5-community
    environment: [ "NEO4J_AUTH=neo4j/neo4jpass" ]
    ports: ["7474:7474","7687:7687"]
    volumes: ["neo4j_data:/data"]

  opensearch:
    image: opensearchproject/opensearch:2
    environment: [ "discovery.type=single-node","bootstrap.memory_lock=true" ]
    ulimits: { memlock: { soft: -1, hard: -1 } }
    ports: ["9200:9200"]
    volumes: ["os_data:/usr/share/opensearch/data"]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes: ["qdrant_data:/qdrant/storage"]

  nats:
    image: nats:2
    command: ["-js"]
    ports: ["4222:4222","8222:8222"]

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=kb_ops
      - POSTGRES_USER=kb
      - POSTGRES_PASSWORD=kbpass
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
    volumes: ["redis_data:/data"]

  # Observability
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./observability/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - ./observability/prometheus/recording_rules.yml:/etc/prometheus/recording_rules.yml
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    ports: ["3000:3000"]

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./observability/loki/config.yml:/etc/loki/config.yml
    ports: ["3100:3100"]

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./observability/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./observability/tempo/config.yaml:/etc/tempo/config.yaml
    ports: ["3200:3200","4317:4317","4318:4318"]

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports: ["9093:9093"]

volumes:
  terminus:
  neo4j_data:
  os_data:
  qdrant_data:
  pg:
  redis_data:
