server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push
scrape_configs:
  - job_name: suricata-eve
    static_configs:
      - targets: [localhost]
        labels:
          job: suricata
          __path__: /var/log/suricata/eve.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            src_ip: src_ip
            dest_ip: dest_ip
            alert: alert
      - labels:
          event_type:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          __path__: /var/log/syslog
      - targets: [localhost]
        labels:
          job: messages
          __path__: /var/log/messages
