version: '3.6'

services:
  api:
    image: localai/localai:latest
    container_name: localai
    ports:
      - "8080:8080"
    environment:
      - MODELS_PATH=/models
      - DEBUG=true
    volumes:
      - ./models:/models
      - ./config:/config
    restart: unless-stopped
