version: "3.9"
services:
  traefik:
    image: traefik:v3
    command:
      - --providers.file.directory=/etc/traefik
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - ./infra/traefik:/etc/traefik
    ports: ["80:80","443:443"]
    depends_on: [bff]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: ["start-dev"]
    environment:
      - KC_DB=dev-mem
    ports: ["8080:8080"]

  bff:
    build: ./services/bff
    env_file: [.env]
    ports: ["8088:8088"]
    depends_on: [terminusdb, neo4j, opensearch, qdrant, nats, postgres]

  terminusdb:
    image: terminusdb/terminusdb-server:latest
    environment:
      - TERMINUSDB_SERVER_PORT=6363
    ports: ["6363:6363"]
    volumes: ["terminus:/data"]

  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
    ports: ["7474:7474","7687:7687"]
    volumes: ["neo4j_data:/data"]

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ["9200:9200"]
    volumes: ["os_data:/usr/share/opensearch/data"]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes: ["qdrant_data:/qdrant/storage"]

  nats:
    image: nats:2
    command: ["-js"]
    ports: ["4222:4222","8222:8222"]

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=kb_ops
      - POSTGRES_USER=kb
      - POSTGRES_PASSWORD=kbpass
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]

volumes:
  terminus:
  neo4j_data:
  os_data:
  qdrant_data:
  pg:
