name = "cloudcurio-stackhub-api"
main = "dist/index.js"
compatibility_date = "2024-11-04"

[vars]
CORS_ALLOW = "*"
REQUIRE_ACCESS = "1"
TURNSTILE_SECRET = ""

[[d1_databases]]
binding = "DB"
database_name = "stackhub_db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[ai]
binding = "AI"

[[vectorize]]
binding   = "VEC"
index_name = "stackhub_index"

[[r2_buckets]]
binding = "ARTIFACTS"
bucket_name = "stackhub-artifacts"

[[queues.producers]]
binding = "EMBED_QUEUE"
queue = "stackhub-embed-queue"

[[queues.consumers]]
queue = "stackhub-embed-queue"
