services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=litellm
      - POSTGRES_DB=analytics
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks: [ ${DOCKER_NETWORK} ]
  analytics-exporter:
    build:
      context: ../exporter
    environment:
      - LITELLM_BASE=http://litellm:${LITELLM_PORT}
      - PGHOST=postgres
      - PGUSER=litellm
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=analytics
    depends_on:
      - postgres
    networks: [ ${DOCKER_NETWORK} ]
