#!/bin/bash

# Cloudflare Tunnel Setup Helper Script for Nextcloud
# This script provides guidance for setting up Cloudflare Tunnel manually

echo "=== Cloudflare Tunnel Setup Helper for Nextcloud ==="
echo ""

# Create documentation directory
DOCS_DIR="/home/cbwinslow/security_setup/docs"
mkdir -p $DOCS_DIR

{
    echo "# Cloudflare Tunnel Setup Helper for Nextcloud"
    echo ""
    echo "Date: $(date)"
    echo ""
    echo "## Setup Instructions"
    echo ""
} > $DOCS_DIR/cloudflare_tunnel_helper.md

# Function to log actions
log_action() {
    echo "$1"
    echo "- $1" >> $DOCS_DIR/cloudflare_tunnel_helper.md
}

echo "This script will guide you through setting up Cloudflare Tunnel for Nextcloud."
log_action "This script will guide you through setting up Cloudflare Tunnel for Nextcloud."

echo ""
echo "Step 1: Obtain Your Cloudflare Certificate"
echo "========================================="
log_action "Step 1: Obtain Your Cloudflare Certificate"
echo ""
echo "1. Visit the Cloudflare dashboard at https://dash.cloudflare.com/"
echo "2. Navigate to Access > Tunnels"
echo "3. Click 'Create a tunnel'"
echo "4. Choose 'Cloudflared' as the connector type"
echo "5. Give your tunnel a name (e.g., 'nextcloud')"
echo "6. Follow the instructions to install the certificate on your system"
echo "7. The certificate will be downloaded automatically or you'll need to"
echo "   manually download it and place it in ~/.cloudflared/cert.pem"

echo ""
echo "Step 2: Create the Tunnel"
echo "========================"
log_action "Step 2: Create the Tunnel"
echo ""
echo "Once you have the certificate, run:"
echo "cloudflared tunnel create nextcloud"
echo ""
echo "This will create a tunnel and generate a UUID for it."

echo ""
echo "Step 3: Configure the Tunnel"
echo "==========================="
log_action "Step 3: Configure the Tunnel"
echo ""
echo "1. Find your tunnel ID:"
echo "   cloudflared tunnel list"
echo ""
echo "2. Create a configuration file at /etc/cloudflared/<TUNNEL_ID>.json:"
echo "   (Replace TUNNEL_ID with your actual tunnel ID)"
echo ""
echo "   {"
echo "     \"tunnel\": \"<TUNNEL_ID>\","
echo "     \"credentials-file\": \"/home/$USER/.cloudflared/<TUNNEL_ID>.json\","
echo "     \"ingress\": ["
echo "       {"
echo "         \"hostname\": \"nextcloud.yourdomain.com\","
echo "         \"service\": \"http://localhost:80\""
echo "       },"
echo "       {"
echo "         \"service\": \"http_status:404\""
echo "       }"
echo "     ]"
echo "   }"

echo ""
echo "Step 4: Route Traffic to Your Tunnel"
echo "==================================="
log_action "Step 4: Route Traffic to Your Tunnel"
echo ""
echo "Route your domain to the tunnel:"
echo "cloudflared tunnel route dns nextcloud nextcloud.yourdomain.com"
echo ""
echo "Make sure nextcloud.yourdomain.com is a domain you own and have"
echo "configured in your Cloudflare account."

echo ""
echo "Step 5: Start the Tunnel"
echo "======================="
log_action "Step 5: Start the Tunnel"
echo ""
echo "Run the tunnel temporarily to test:"
echo "cloudflared tunnel --config /etc/cloudflared/<TUNNEL_ID>.json run"
echo ""
echo "Or install as a service for production use:"
echo "sudo cloudflared service install --config /etc/cloudflared/<TUNNEL_ID>.json"
echo "sudo systemctl enable cloudflared"
echo "sudo systemctl start cloudflared"

echo ""
echo "Step 6: Access Your Nextcloud"
echo "============================"
log_action "Step 6: Access Your Nextcloud"
echo ""
echo "Once the tunnel is running, you can access your Nextcloud at:"
echo "https://nextcloud.yourdomain.com"
echo ""
echo "The first time you access it, you'll need to complete the"
echo "Nextcloud setup wizard."

echo ""
echo "Step 7: Secure Your Installation"
echo "==============================="
log_action "Step 7: Secure Your Installation"
echo ""
echo "1. Configure Cloudflare Access for authentication:"
echo "   - In the Cloudflare dashboard, go to Access > Applications"
echo "   - Create a new application for your Nextcloud domain"
echo "   - Configure authentication methods (Google, GitHub, etc.)"
echo "   - Set up access policies as needed"
echo ""
echo "2. Enable two-factor authentication in Nextcloud:"
echo "   - Once Nextcloud is set up, go to Settings > Security"
echo "   - Enable two-factor authentication"
echo ""
echo "3. Set up SSL/TLS in Cloudflare:"
echo "   - In the Cloudflare dashboard, go to SSL/TLS > Overview"
echo "   - Set SSL/TLS encryption mode to 'Full' or 'Full (strict)'"
echo "   - Enable 'Always Use HTTPS' in SSL/TLS > Edge Certificates"

{
    echo ""
    echo "## Useful Commands"
    echo ""
    echo "- Check tunnel status: cloudflared tunnel list"
    echo "- View tunnel logs: sudo journalctl -u cloudflared -f"
    echo "- Validate configuration: cloudflared tunnel validate --config /etc/cloudflared/<TUNNEL_ID>.json"
    echo "- Check tunnel info: cloudflared tunnel info nextcloud"
    echo ""
    echo "## Troubleshooting"
    echo ""
    echo "- If the tunnel won't start, check the configuration file permissions"
    echo "- Ensure the domain is correctly routed in the Cloudflare dashboard"
    echo "- Check firewall settings if you're having connectivity issues"
    echo "- Verify that Nextcloud is running locally at http://localhost/nextcloud"
    echo "- Check Cloudflare certificate validity and permissions"
    echo ""
    echo "## Security Recommendations"
    echo ""
    echo "- Use Cloudflare Access for authentication"
    echo "- Enable two-factor authentication in Nextcloud"
    echo "- Use strong, unique passwords"
    echo "- Keep cloudflared updated regularly"
    echo "- Monitor access logs regularly"
    echo "- Use Cloudflare's built-in security features (WAF, Rate Limiting)"
    echo "- Regularly review and update access policies"
    echo ""
    echo "## Next Steps"
    echo ""
    echo "1. Complete the manual setup steps above"
    echo "2. Access your Nextcloud at https://nextcloud.yourdomain.com"
    echo "3. Complete the initial Nextcloud setup"
    echo "4. Configure authentication and security settings"
    echo "5. Set up regular backups"
    echo "6. Monitor logs and set up alerts"
} >> $DOCS_DIR/cloudflare_tunnel_helper.md

log_action "Setup instructions complete!"

echo ""
echo "=== Setup Instructions Complete ==="
echo "Documentation created in $DOCS_DIR/cloudflare_tunnel_helper.md"
echo ""
echo "Next steps:"
echo "1. Follow the manual setup instructions in the documentation"
echo "2. Complete the Cloudflare Tunnel setup with your actual certificate"
echo "3. Access your Nextcloud at https://nextcloud.yourdomain.com"
echo "4. Complete the initial Nextcloud setup through the web interface"