#!/bin/bash

# Getting Started Script
# This script provides a quick start guide for the immediate next steps

echo "=== Getting Started with Your Security Setup ==="
echo ""

# Display welcome message
echo "Welcome to your security setup! This script will guide you through the immediate next steps."
echo ""

# Display current status
echo "Current Status:"
echo "==============="
echo "- Core infrastructure: ✅ Installed"
echo "- Security tools: ✅ Installed (configuration pending)"
echo "- Nextcloud: ⚠️  Files downloaded but not installed"
echo "- Cloudflare Tunnel: ⚠️  Client installed but not configured"
echo ""

# Display immediate next steps
echo "Immediate Next Steps:"
echo "===================="
echo ""
echo "1. Deploy Nextcloud"
echo "------------------"
echo "Run the deployment script:"
echo "   /home/cbwinslow/security_setup/deploy_nextcloud_simple.sh"
echo ""
echo "This will:"
echo "- Move Nextcloud files to /var/www/nextcloud"
echo "- Set proper ownership for Nextcloud files"
echo "- Create Nextcloud configuration files"
echo "- Restart Apache to apply changes"
echo ""
echo "After deployment, access Nextcloud at http://localhost/nextcloud"
echo "and complete the initial setup wizard."
echo ""
echo "2. Configure Cloudflare Tunnel"
echo "------------------------------"
echo "Follow the manual setup instructions in:"
echo "   /home/cbwinslow/security_setup/docs/manual_cloudflare_tunnel_cloudcurio.md"
echo ""
echo "This will:"
echo "- Replace placeholder certificate with actual Cloudflare certificate"
echo "- Create tunnel for nextcloud"
echo "- Configure tunnel routing for cloudcurio.cc"
echo "- Start tunnel service"
echo ""
echo "After configuration, access Nextcloud at https://cloudcurio.cc/nextcloud"
echo ""
echo "3. Secure Your Installation"
echo "----------------------------"
echo "Enable two-factor authentication in Nextcloud:"
echo "- Once Nextcloud is set up, go to Settings > Security"
echo "- Enable two-factor authentication"
echo ""
echo "Configure Cloudflare Access for authentication:"
echo "- In the Cloudflare dashboard, go to Access > Applications"
echo "- Create a new application for your Nextcloud domain"
echo "- Configure authentication methods (Google, GitHub, etc.)"
echo "- Set up access policies as needed"
echo ""
echo "Set up SSL/TLS in Cloudflare:"
echo "- In the Cloudflare dashboard, go to SSL/TLS > Overview"
echo "- Set SSL/TLS encryption mode to 'Full' or 'Full (strict)'"
echo "- Enable 'Always Use HTTPS' in SSL/TLS > Edge Certificates"
echo ""
echo "4. Set Up Backups"
echo "-----------------"
echo "Configure automated backups for Nextcloud data:"
echo "- Set up regular database backups"
echo "- Configure file backup strategy"
echo "- Test restoration procedures"
echo "- Store backups in secure location"
echo ""
echo "5. Monitor Your Installation"
echo "----------------------------"
echo "Check Apache logs for errors:"
echo "   sudo tail -f /var/log/apache2/error.log"
echo ""
echo "Monitor Nextcloud activity logs:"
echo "   sudo tail -f /var/log/apache2/nextcloud_*.log"
echo ""
echo "Set up basic monitoring alerts:"
echo "   - Disk space monitoring"
echo "   - Memory usage monitoring"
echo "   - CPU usage monitoring"
echo "   - Network connectivity monitoring"
echo ""
echo "Review system resource usage:"
echo "   - Disk space: df -h"
echo "   - Memory usage: free -h"
echo "   - CPU usage: top or htop"
echo "   - Network usage: iftop or nethogs"
echo ""

# Display documentation links
echo "Documentation Links:"
echo "==================="
echo ""
echo "Main documentation directory:"
echo "   /home/cbwinslow/security_setup/docs/"
echo ""
echo "Key documents:"
echo "   - deployment_summary.md: Complete deployment summary"
echo "   - immediate_next_steps.md: Immediate next steps checklist"
echo "   - manual_cloudflare_tunnel_cloudcurio.md: Manual Cloudflare Tunnel setup guide"
echo "   - cloudflare_tunnel_checklist.md: Cloudflare Tunnel setup checklist"
echo "   - verification_results.md: Verification results"
echo "   - status_report.md: Status report output"
echo ""
echo "Scripts directory:"
echo "   /home/cbwinslow/security_setup/"
echo ""
echo "Key scripts:"
echo "   - deploy_nextcloud_simple.sh: Nextcloud deployment script"
echo "   - setup_cloudflare_tunnel.sh: Cloudflare Tunnel setup script"
echo "   - verify_security_setup.sh: Verification script"
echo "   - troubleshoot.sh: Troubleshooting script"
echo "   - status_report.sh: Status reporting script"
echo ""

# Display troubleshooting resources
echo "Troubleshooting Resources:"
echo "========================="
echo ""
echo "Common issues and solutions:"
echo "1. Apache not starting:"
echo "   - Check configuration with 'sudo apache2ctl configtest'"
echo "   - Check error logs in /var/log/apache2/error.log"
echo ""
echo "2. Nextcloud not accessible:"
echo "   - Verify file permissions in /var/www/nextcloud"
echo "   - Check Apache virtual host configuration"
echo "   - Ensure required Apache modules are enabled"
echo ""
echo "3. Cloudflare Tunnel not connecting:"
echo "   - Verify certificate validity"
echo "   - Check tunnel configuration"
echo "   - Ensure network connectivity"
echo ""
echo "4. Database connection issues:"
echo "   - Verify PostgreSQL is running"
echo "   - Check database user permissions"
echo "   - Verify connection settings in configuration files"
echo ""
echo "Useful commands:"
echo "- Check service status: systemctl status SERVICE_NAME"
echo "- Restart service: systemctl restart SERVICE_NAME"
echo "- View logs: journalctl -u SERVICE_NAME -f"
echo "- Check network connectivity: ping, traceroute, nslookup"
echo "- Check port usage: netstat -tlnp, ss -tlnp"
echo "- Check disk space: df -h"
echo "- Check memory usage: free -h"
echo ""

# Display maintenance schedule
echo "Maintenance Schedule:"
echo "===================="
echo ""
echo "Daily:"
echo "- Check service status"
echo "- Review security logs"
echo "- Verify backups"
echo ""
echo "Weekly:"
echo "- Apply security updates"
echo "- Run vulnerability scans"
echo "- Review firewall rules"
echo ""
echo "Monthly:"
echo "- Full system updates"
echo "- Rotate logs"
echo "- Test disaster recovery procedures"
echo "- Review security configurations"
echo ""

# Display conclusion
echo "Conclusion:"
echo "==========="
echo ""
echo "Your security setup is well underway with a solid foundation established."
echo "The immediate priorities are completing the Nextcloud deployment and"
echo "configuring Cloudflare Tunnel for secure external access."
echo ""
echo "Once these are complete, you can proceed with configuring the monitoring"
echo "tools and eventually installing the threat intelligence and penetration"
echo "testing platforms."
echo ""
echo "All necessary scripts and documentation are in place to guide you through"
echo "the remaining steps. The modular approach of your setup allows you to"
echo "complete components at your own pace based on your priorities and requirements."
echo ""
echo "For any issues or questions, refer to the documentation in"
echo "/home/cbwinslow/security_setup/docs/ or run the troubleshooting script at"
echo "/home/cbwinslow/security_setup/troubleshoot.sh."
echo ""
echo "Happy securing!"