#!/bin/bash

# Manual Cloudflare Tunnel Setup Guide for cloudcurio.cc/nextcloud
# This script provides manual instructions for setting up Cloudflare Tunnel

echo "=== Manual Cloudflare Tunnel Setup Guide for cloudcurio.cc/nextcloud ==="
echo ""

{
    echo "# Manual Cloudflare Tunnel Setup Guide for cloudcurio.cc/nextcloud"
    echo ""
    echo "Date: $(date)"
    echo ""
    echo "## Manual Setup Instructions"
    echo ""
} > /home/cbwinslow/security_setup/docs/manual_cloudflare_tunnel_cloudcurio.md

# Function to log actions
log_action() {
    echo "$1"
    echo "- $1" >> /home/cbwinslow/security_setup/docs/manual_cloudflare_tunnel_cloudcurio.md
}

echo "This guide provides manual instructions for setting up Cloudflare Tunnel for your domain cloudcurio.cc/nextcloud."
log_action "This guide provides manual instructions for setting up Cloudflare Tunnel for your domain cloudcurio.cc/nextcloud."

echo ""
echo "Step 1: Replace the Placeholder Certificate"
echo "========================================="
log_action "Step 1: Replace the Placeholder Certificate"
echo ""
echo "1. Visit the Cloudflare dashboard at https://dash.cloudflare.com/"
echo "2. Navigate to Access > Tunnels"
echo "3. Click 'Create a tunnel'"
echo "4. Choose 'Cloudflared' as the connector type"
echo "5. Give your tunnel a name (e.g., 'nextcloud')"
echo "6. Follow the instructions to install the certificate on your system"
echo "7. The certificate will be downloaded automatically to ~/.cloudflared/"
echo ""
echo "After downloading, replace the placeholder certificate:"
echo "cp ~/.cloudflared/*.pem /home/cbwinslow/.cloudflared/cert.pem"
echo "sudo chown cbwinslow:cbwinslow /home/cbwinslow/.cloudflared/cert.pem"
echo "chmod 600 /home/cbwinslow/.cloudflared/cert.pem"

log_action "Commands to run manually after downloading certificate:"
log_action "cp ~/.cloudflared/*.pem /home/cbwinslow/.cloudflared/cert.pem"
log_action "sudo chown cbwinslow:cbwinslow /home/cbwinslow/.cloudflared/cert.pem"
log_action "chmod 600 /home/cbwinslow/.cloudflared/cert.pem"

echo ""
echo "Step 2: Create the Tunnel"
echo "========================"
log_action "Step 2: Create the Tunnel"
echo ""
echo "Run the following command manually:"
echo "cloudflared tunnel create nextcloud"
echo ""
echo "This will create a tunnel and generate a UUID for it."

log_action "Command to run manually:"
log_action "cloudflared tunnel create nextcloud"

echo ""
echo "Step 3: Find Your Tunnel ID"
echo "=========================="
log_action "Step 3: Find Your Tunnel ID"
echo ""
echo "Run the following command manually:"
echo "cloudflared tunnel list"
echo ""
echo "Note the tunnel ID (UUID) from the output."

log_action "Command to run manually:"
log_action "cloudflared tunnel list"

echo ""
echo "Step 4: Create Tunnel Configuration"
echo "=================================="
log_action "Step 4: Create Tunnel Configuration"
echo ""
echo "Replace TUNNEL_ID with your actual tunnel ID from the previous step:"
echo ""
echo "sudo mkdir -p /etc/cloudflared"
echo ""
echo "sudo tee /etc/cloudflared/TUNNEL_ID.json > /dev/null <<EOF"
echo "{"
echo "  \"tunnel\": \"TUNNEL_ID\","
echo "  \"credentials-file\": \"/home/cbwinslow/.cloudflared/TUNNEL_ID.json\","
echo "  \"ingress\": ["
echo "    {"
echo "      \"hostname\": \"cloudcurio.cc\","
echo "      \"service\": \"http://localhost:80\""
echo "    },"
echo "    {"
echo "      \"service\": \"http_status:404\""
echo "    }"
echo "  ]"
echo "}"
echo "EOF"

log_action "Commands to run manually (replace TUNNEL_ID with actual ID):"
log_action "sudo mkdir -p /etc/cloudflared"
log_action "sudo tee /etc/cloudflared/TUNNEL_ID.json > /dev/null <<EOF (see above for content)"

echo ""
echo "Step 5: Route Traffic to Your Tunnel"
echo "==================================="
log_action "Step 5: Route Traffic to Your Tunnel"
echo ""
echo "Run the following command manually (replace TUNNEL_ID with your actual tunnel ID):"
echo "cloudflared tunnel route dns TUNNEL_ID cloudcurio.cc"

log_action "Command to run manually (replace TUNNEL_ID with actual ID):"
log_action "cloudflared tunnel route dns TUNNEL_ID cloudcurio.cc"

echo ""
echo "Step 6: Start the Tunnel"
echo "======================="
log_action "Step 6: Start the Tunnel"
echo ""
echo "To run the tunnel temporarily for testing:"
echo "cloudflared tunnel --config /etc/cloudflared/TUNNEL_ID.json run"
echo ""
echo "To install as a service for production use:"
echo "sudo cloudflared service install --config /etc/cloudflared/TUNNEL_ID.json"
echo "sudo systemctl enable cloudflared"
echo "sudo systemctl start cloudflared"

log_action "Commands to run manually (replace TUNNEL_ID with actual ID):"
log_action "For testing: cloudflared tunnel --config /etc/cloudflared/TUNNEL_ID.json run"
log_action "For production: sudo cloudflared service install --config /etc/cloudflared/TUNNEL_ID.json"
log_action "sudo systemctl enable cloudflared"
log_action "sudo systemctl start cloudflared"

echo ""
echo "Step 7: Access Your Nextcloud"
echo "============================"
log_action "Step 7: Access Your Nextcloud"
echo ""
echo "Once the tunnel is running, you can access your Nextcloud at:"
echo "https://cloudcurio.cc/nextcloud"
echo ""
echo "The first time you access it, you'll need to complete the"
echo "Nextcloud setup wizard."

log_action "Access your Nextcloud at:"
log_action "https://cloudcurio.cc/nextcloud"

echo ""
echo "Step 8: Secure Your Installation"
echo "==============================="
log_action "Step 8: Secure Your Installation"
echo ""
echo "1. Configure Cloudflare Access for authentication:"
echo "   - In the Cloudflare dashboard, go to Access > Applications"
echo "   - Create a new application for your Nextcloud domain"
echo "   - Configure authentication methods (Google, GitHub, etc.)"
echo "   - Set up access policies as needed"
echo ""
echo "2. Enable two-factor authentication in Nextcloud:"
echo "   - Once Nextcloud is set up, go to Settings > Security"
echo "   - Enable two-factor authentication"
echo ""
echo "3. Set up SSL/TLS in Cloudflare:"
echo "   - In the Cloudflare dashboard, go to SSL/TLS > Overview"
echo "   - Set SSL/TLS encryption mode to 'Full' or 'Full (strict)'"
echo "   - Enable 'Always Use HTTPS' in SSL/TLS > Edge Certificates"

log_action "Security recommendations:"
log_action "1. Configure Cloudflare Access for authentication"
log_action "2. Enable two-factor authentication in Nextcloud"
log_action "3. Set up SSL/TLS in Cloudflare"

{
    echo ""
    echo "## Useful Commands"
    echo ""
    echo "- Check tunnel status: cloudflared tunnel list"
    echo "- View tunnel logs: sudo journalctl -u cloudflared -f"
    echo "- Validate configuration: cloudflared tunnel validate --config /etc/cloudflared/TUNNEL_ID.json"
    echo "- Check tunnel info: cloudflared tunnel info nextcloud"
    echo ""
    echo "## Troubleshooting"
    echo ""
    echo "- If the tunnel won't start, check the configuration file permissions"
    echo "- Ensure the domain is correctly routed in the Cloudflare dashboard"
    echo "- Check firewall settings if you're having connectivity issues"
    echo "- Verify that Nextcloud is running locally at http://localhost/nextcloud"
    echo "- Check Cloudflare certificate validity and permissions"
    echo ""
    echo "## Security Recommendations"
    echo ""
    echo "- Use Cloudflare Access for authentication"
    echo "- Enable two-factor authentication in Nextcloud"
    echo "- Use strong, unique passwords"
    echo "- Keep cloudflared updated regularly"
    echo "- Monitor access logs regularly"
    echo "- Use Cloudflare's built-in security features (WAF, Rate Limiting)"
    echo "- Regularly review and update access policies"
    echo ""
    echo "## Next Steps"
    echo ""
    echo "1. Complete the manual setup steps above"
    echo "2. Access your Nextcloud at https://cloudcurio.cc/nextcloud"
    echo "3. Complete the initial Nextcloud setup"
    echo "4. Configure authentication and security settings"
    echo "5. Set up regular backups"
    echo "6. Monitor logs and set up alerts"
} >> /home/cbwinslow/security_setup/docs/manual_cloudflare_tunnel_cloudcurio.md

log_action "Manual setup instructions complete!"
echo ""
echo "=== Manual Setup Instructions Complete ==="
echo "Documentation created in /home/cbwinslow/security_setup/docs/manual_cloudflare_tunnel_cloudcurio.md"
echo ""
echo "Next steps:"
echo "1. Follow the manual setup instructions in the documentation"
echo "2. Complete the Cloudflare Tunnel setup with your actual certificate"
echo "3. Access your Nextcloud at https://cloudcurio.cc/nextcloud"
echo "4. Complete the initial Nextcloud setup through the web interface"